# $Id: Makefile 1473 2011-04-01 00:09:31Z davidpiegdon $
# libalf dispatcher Makefile

.PHONY: all clean install uninstall

all:
	+make -C src all

clean:
	make -C src clean

install:
	+make -C src install

uninstall:
	make -C src uninstall

