# $Id: Makefile 1446 2011-02-28 16:57:56Z davidpiegdon $
# libalf-interfaces testsuite Makefile

.PHONY: all clean  biermann_original

all: biermann_original


biermann_original:
	+make -C biermann_original


clean:
	make -C biermann_original clean

